version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mydb  # Database name
    ports:
      - "5432:5432"  # Exposing PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data

volumes:
  postgres-data:
